package mybatis_generate.model.hs_haa;

public class RedevProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PRJ_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpPrjCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ACTIVE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpCreateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpCreateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_DESCRIPTION
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ESTATE_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpEstateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_FLAT_SORT_CONFIG
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private Integer rpFlatSortConfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_APP_NEXT_SEQ
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private Long rpAppNextSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PROP_RANGE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpPropRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpUpdateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    private String rpUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PRJ_CODE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_PRJ_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpPrjCode() {
        return rpPrjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PRJ_CODE
     *
     * @param rpPrjCode the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_PRJ_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpPrjCode(String rpPrjCode) {
        this.rpPrjCode = rpPrjCode == null ? null : rpPrjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ACTIVE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_ACTIVE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpActive() {
        return rpActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ACTIVE
     *
     * @param rpActive the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_ACTIVE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpActive(String rpActive) {
        this.rpActive = rpActive == null ? null : rpActive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_BY
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpCreateBy() {
        return rpCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_BY
     *
     * @param rpCreateBy the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpCreateBy(String rpCreateBy) {
        this.rpCreateBy = rpCreateBy == null ? null : rpCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_DATE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpCreateDate() {
        return rpCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_DATE
     *
     * @param rpCreateDate the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_CREATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpCreateDate(String rpCreateDate) {
        this.rpCreateDate = rpCreateDate == null ? null : rpCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_DESCRIPTION
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_DESCRIPTION
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpDescription() {
        return rpDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_DESCRIPTION
     *
     * @param rpDescription the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_DESCRIPTION
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpDescription(String rpDescription) {
        this.rpDescription = rpDescription == null ? null : rpDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ESTATE_CODE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_ESTATE_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpEstateCode() {
        return rpEstateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_ESTATE_CODE
     *
     * @param rpEstateCode the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_ESTATE_CODE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpEstateCode(String rpEstateCode) {
        this.rpEstateCode = rpEstateCode == null ? null : rpEstateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_FLAT_SORT_CONFIG
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_FLAT_SORT_CONFIG
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public Integer getRpFlatSortConfig() {
        return rpFlatSortConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_FLAT_SORT_CONFIG
     *
     * @param rpFlatSortConfig the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_FLAT_SORT_CONFIG
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpFlatSortConfig(Integer rpFlatSortConfig) {
        this.rpFlatSortConfig = rpFlatSortConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_APP_NEXT_SEQ
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_APP_NEXT_SEQ
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public Long getRpAppNextSeq() {
        return rpAppNextSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_APP_NEXT_SEQ
     *
     * @param rpAppNextSeq the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_APP_NEXT_SEQ
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpAppNextSeq(Long rpAppNextSeq) {
        this.rpAppNextSeq = rpAppNextSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PROP_RANGE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_PROP_RANGE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpPropRange() {
        return rpPropRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_PROP_RANGE
     *
     * @param rpPropRange the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_PROP_RANGE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpPropRange(String rpPropRange) {
        this.rpPropRange = rpPropRange == null ? null : rpPropRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_BY
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpUpdateBy() {
        return rpUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_BY
     *
     * @param rpUpdateBy the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_BY
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpUpdateBy(String rpUpdateBy) {
        this.rpUpdateBy = rpUpdateBy == null ? null : rpUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_DATE
     *
     * @return the value of HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public String getRpUpdateDate() {
        return rpUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_DATE
     *
     * @param rpUpdateDate the value for HS_HAA.HST_HAA_REDEV_PROJECT.RP_UPDATE_DATE
     *
     * @mbg.generated Thu Nov 03 17:49:24 CST 2022
     */
    public void setRpUpdateDate(String rpUpdateDate) {
        this.rpUpdateDate = rpUpdateDate == null ? null : rpUpdateDate.trim();
    }
}